### ISSUE TITLE
Missing character encoding in response header

### ISSUE THREAD

**Issue by jmkeil** [gfbio/terminology-service#10]
Please provide the encoding (UTF-8) in the response header.

**Comment by jmkeil** [comment]
I just learned, that JSON is required to be encoded using UTF-8, UTF-16 or UTF-32 and adding an _charset_ parameter must have no effect on compliant recipients. (see https://tools.ietf.org/html/rfc7159#page-11) Therefore, this is a proper implementation. But adding the parameter might help noncompliant recipients.

**Comment by DavidFichtmueller** [comment]
This has been fixed in the 3.0 release in March 2018, but wasn't properly documented in the change set.
