### ISSUE TITLE
How fast will new terms from Geonames appear in Terminology Server?

### ISSUE THREAD

**Issue by jmkeil** [gfbio/terminology-service#11]
How fast will new terms from Geonames appear in the Terminology Server?

I have added a new term on Geonames, but currently asking the Terminology Server about that IRI will result in an IndexOutOfBoundsException message: https://terminologies.gfbio.org/api/terminologies/GEONAMES/term?uri=http://sws.geonames.org/11611800/

**Comment by jmkeil** [comment]
It was available a few days later.

**Comment by DavidFichtmueller** [comment]
The terms are available in the Terminology Service, as soon as they are available in the Geonames Webservice. However, it takes a while (not sure how long) until newly created terms become available there. For example when you look at the [Recent Changes](http://www.geonames.org/recent-changes.html) and select one of the items that were newly created, then feature already has a regular page (formatted like: http://www.geonames.org/11695917 ), but is not available in the webservice yet (http://sws.geonames.org/11695917 current example as of the minute I am writing this).
However the TS needs to do a better error handling when the term is not available. Thanks for pointing this out.
