### ISSUE TITLE
URIs of GEONAMES must end with a "/"

### ISSUE THREAD

**Issue by jmkeil** [gfbio/terminology-service#12]
The URIs provided for Geonames should end with a `/`, as this is the official notation (see http://www.geonames.org/ontology/documentation.html).

E.g. `.../search?query=Berlin&terminologies=GEONAMES&match_type=included` currently provides 
`http://www.geonames.org/2950159` (live) or `http://sws.geonames.org/2950159` (demo) but should provide  `http://sws.geonames.org/2950159/`.

**Comment by DavidFichtmueller** [comment]
Now solved on the regular server as well, after the most recent release.
