### ISSUE TITLE
missing terminology parameter in suggest service

### ISSUE THREAD

**Issue by jmkeil** [gfbio/terminology-service#2]
The suggest service does not provide a terminology parameter. Of course it is possible to filter not required results. But reducing the number of terminologies to process might improve the response time, doesn't it?

**Comment by ikostadi** [comment]
+1 for a terminology filter in the suggest service

**Comment by naouelkaram** [comment]
This was planned for a while and I finally added the parameter to the suggest endpoint, available on dev and soon live with the next release: 
http://dev-gfbio.bgbm.org/api/terminologies/suggest?query=prov&terminologies=ENVO
http://dev-gfbio.bgbm.org/api/terminologies/suggest?query=prov&terminologies=CHEBI,ENVO&limit=50

**Comment by DavidFichtmueller** [comment]
Now solved on the regular server as well, after the most recent release.
