### ISSUE TITLE
URI prefix of GEONAMES

### ISSUE THREAD

**Issue by jmkeil** [gfbio/terminology-service#3]
The URIs provided for GEONAMES have the prefix "http://www.geonames.org/", but the GEONAMES People intended "http://sws.geonames.org/" as prefix of their identifiers (see http://www.geonames.org/ontology/documentation.html )

**Comment by naouelkaram** [comment]
Solved in Dev: http://dev-gfbio.bgbm.org/api/terminologies/search?query=London&terminologies=GEONAMES
Namespace included: http://dev-gfbio.bgbm.org/api/terminologies/GEONAMES/

**Comment by jmkeil** [comment]
Thank you.

**Comment by DavidFichtmueller** [comment]
Now solved on the regular server as well, after the most recent release.
