### ISSUE TITLE
min query length validation of suggest service

### ISSUE THREAD

**Issue by jmkeil** [gfbio/terminology-service#4]
In the suggestion service the min length of 4 applies also for suffixes not only the whole term:

http://terminologies.gfbio.org/api/terminologies/suggest?query=per
-> error (expected)

http://terminologies.gfbio.org/api/terminologies/suggest?query=meter+per+seco
-> no error (expected)

http://terminologies.gfbio.org/api/terminologies/suggest?query=meter+per
-> error (not expected)

**Comment by naouelkaram** [comment]
This is due to the fulltext index restriction, I will update the documentation accordingly. Is the warning message "The service does not return results for wildcard queries with less than 4 leading characters" clear?

**Comment by jmkeil** [comment]
So this can not be fixed?

I think this warning message does not cover the third case. "metre per" has 4 leading character but will fail anyhow.

**Comment by naouelkaram** [comment]
Yes this comes from the triple store restriction. If it is a big issue, there is an option to recompile the source code with a smaller limit.
I will change the text to cover the 3rd case.

**Comment by naouelkaram** [comment]
The warning text changed accordingly
