### ISSUE TITLE
CHEBI search restrictions

### ISSUE THREAD

**Issue by jmkeil** [gfbio/terminology-service#8]
The search interface on https://www.ebi.ac.uk/chebi/webServices.do provides results for e.g. `H2O` or `(H2O)nO5SV`, but the terminology server does not. Is the result filtered anyhow or restricted to some search categories? Can that filter/restriction be weakened?

**Comment by naouelkaram** [comment]
Solved in Dev http://dev-gfbio.bgbm.org/api/terminologies/search?query=H2O
Latest version of CHEBI (2017-06-02) will be available with the upcoming release (first week of July)

**Comment by jmkeil** [comment]
Thank you very much.

**Comment by jmkeil** [comment]
Sorry, but for `(H2O)nO5SV` it still not works.

**Comment by naouelkaram** [comment]
Solved on dev: https://dev-gfbio.bgbm.org/api/terminologies/search?query=(H2O)nO5SV&terminologies=CHEBI

**Comment by DavidFichtmueller** [comment]
Now solved on the regular server as well, after the most recent release.
